name: avaz_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.2.0
  flutter_tts: ^4.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  volume_controller: ^2.0.8
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  file_picker: ^8.1.4
  audioplayers: ^6.1.0
  flutter_sound: ^9.17.5
  auto_size_text: ^3.0.0
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/grid_icons/
    
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito.ttf

    - family: NunitoBold
      fonts:
        - asset: fonts/nunitobold.ttf

    - family: NunitoItalic
      fonts:
        - asset: fonts/nunitoitalic.ttf

    - family: NunitoLight
      fonts:
        - asset: fonts/nunitolight.ttf

    - family: NunitoSans
      fonts:
        - asset: fonts/nunitosans.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #